name: 'Build and Install MoltenVK and DXVK'
description: 'Action that builds MoltenVK and DXVK and bundles them in a common installation'
inputs:
  crossover-source:
    description: 'Path to the crossover source (i.e. the directory that contains the "moltenvk" and "dxvk" directories'
    required: true
    default: ${{ github.workspace }}/sources
  install-prefix:
    description: 'Installation target directory for MoltenVK and DXVK'
    required: true
    # default: ${{ env.INSTALLROOT }}/${{ env.MOLTENVK_DXVK_INSTALLATION }}

runs:
  using: "composite"
  steps:

    - name: Applying patches to DXVK
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/dxvk
        patch -p1 < ${{ github.workspace }}/0001-build-macOS-Fix-up-for-macOS.patch
        patch -p1 < ${{ github.workspace }}/0002-fix-d3d11-header-for-MinGW-9-1883.patch
        patch -p1 < ${{ github.workspace }}/0003-fixes-for-mingw-gcc-12.patch
        popd

    - name: test
      shell: bash
      run: |
        ln -sf /usr/local/bin/c++-12 /usr/local/bin/c++
        ln -sf /usr/local/bin/cpp-12 /usr/local/bin/cpp
        ln -sf /usr/local/bin/g++-12 /usr/local/bin/g++
        ln -sf /usr/local/bin/gcc-12 /usr/local/bin/gcc
        ln -sf /usr/local/bin/gcc-ar-12 /usr/local/bin/gcc-ar
        ln -sf /usr/local/bin/gcc-nm-12 /usr/local/bin/gcc-nm
        ln -sf /usr/local/bin/gcc-ranlib-12 /usr/local/bin/gcc-ranlib
        ln -sf /usr/local/bin/gcov-12 /usr/local/bin/gcov
        ln -sf /usr/local/bin/gcov-dump-12 /usr/local/bin/gcov-dump
        ln -sf /usr/local/bin/gcov-tool-12 /usr/local/bin/gcov-tool
        ln -sf /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
        ln -sf /usr/local/bin/lto-dump-12 /usr/local/bin/lto-dump

        export PATH="/usr/local/bin:$PATH"

        which gcc
        gcc --version

        which cpp
        cpp --version

    - name: Install distutils
      shell: bash
      run: |
        python --version
        pip install setuptools
        python --version
        pip install --upgrade setuptools

    ############ Build and Install MoltenVK ##############
    - name: Build MoltenVK
      shell: bash
      run: |
        pushd ${{ inputs.crossover-source }}/moltenvk
        ./fetchDependencies --macos
        make macos
        popd

    - name: Install MoltenVK
      shell: bash
      run: |
        set -x

        pushd ${{ inputs.crossover-source }}/moltenvk/Package/Latest/MoltenVK
        mkdir -p ${{ inputs.install-prefix }}/usr/local/lib/
        cp ./dylib/macOS/*.dylib ${{ inputs.install-prefix }}/usr/local/lib/
        cp -r ./include ${{ inputs.install-prefix }}/usr/local/
        popd

        # also copy the spirv-headers as VKD3D seems to need them for building
        pushd ${{ inputs.crossover-source }}/moltenvk/External/glslang/External/spirv-tools/external/spirv-headers/include/
        cp -r ./spirv ${{ inputs.install-prefix }}/usr/local/include/

        popd

    ############ Build and Install DXVK ##############
    - name: Get latest HomeBrew formulas/bottles
      shell: bash
      run: |
        brew update

    - name: Install Dependencies for DXVK
      shell: bash
      run: |
        brew install  glslang   \
                      meson

        wget https://raw.githubusercontent.com/Homebrew/homebrew-core/d5ec00528f86b8ac31fac2a67b7667cc72aa1b04/Formula/mingw-w64.rb -O mingw-w64.rb
        brew install mingw-w64.rb

    - name: Build DXVK
      shell: bash
      run: |
        set -x
        pushd ${{ inputs.crossover-source }}/dxvk

        ./package-release.sh master ${{ inputs.crossover-source }}/dxvk/install --no-package
        popd

    - name: Install DXVK
      shell: bash
      run: |
        set -x
        pushd ${{ inputs.crossover-source }}/dxvk/install/dxvk-macOS-master

        echo Installing DXVK dlls...
        mkdir -p ${{ inputs.install-prefix }}/usr/local/lib64/wine
        cp -r x64 ${{ inputs.install-prefix }}/usr/local/lib64/wine/dxvk

        echo Installing DXVK setup script...
        mkdir -p ${{ inputs.install-prefix }}/usr/local/bin
        cp setup_dxvk.sh ${{ inputs.install-prefix }}/usr/local/bin/

        popd
